/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export const STICKER_NAMES: Record<string, { name: string; team: string }> = {
  // Specials
  "00": { "name": "Panini Logo", "team": "We Are Panini" },
  "FWC1": { "name": "Official Emblem1", "team": "FIFA World Cup 2026" },
  "FWC2": { "name": "Official Emblem2", "team": "FIFA World Cup 2026" },
  "FWC3": { "name": "Official Mascots", "team": "FIFA World Cup 2026" },
  "FWC4": { "name": "Official Slogan", "team": "FIFA World Cup 2026" },
  "FWC5": { "name": "Official Ball", "team": "FIFA World Cup 2026" },
  "FWC6": { "name": "Canada", "team": "Host Countries and Cities" },
  "FWC7": { "name": "Mexico", "team": "Host Countries and Cities" },
  "FWC8": { "name": "USA", "team": "Host Countries and Cities" },
  "FWC9": { "name": "Italy 1934", "team": "FIFA World Cup History" },
  "FWC10": { "name": "Uruguay 1950", "team": "FIFA World Cup History" },
  "FWC11": { "name": "West Germany 1954", "team": "FIFA World Cup History" },
  "FWC12": { "name": "Brazil 1962", "team": "FIFA World Cup History" },
  "FWC13": { "name": "West Germany 1974", "team": "FIFA World Cup History" },
  "FWC14": { "name": "Argentina 1986", "team": "FIFA World Cup History" },
  "FWC15": { "name": "Brazil 1994", "team": "FIFA World Cup History" },
  "FWC16": { "name": "Brazil 2002", "team": "FIFA World Cup History" },
  "FWC17": { "name": "Italy 2006", "team": "FIFA World Cup History" },
  "FWC18": { "name": "Germany 2014", "team": "FIFA World Cup History" },
  "FWC19": { "name": "Argentina 2022", "team": "FIFA World Cup History" },

  // Mexico
  "MEX1": { "name": "Escudo (Emblem)", "team": "Mexico" },
  "MEX2": { "name": "Luis Malagón", "team": "Mexico" },
  "MEX3": { "name": "Johan Vasquez", "team": "Mexico" },
  "MEX4": { "name": "Jorge Sánchez", "team": "Mexico" },
  "MEX5": { "name": "Cesar Montes", "team": "Mexico" },
  "MEX6": { "name": "Jesus Gallardo", "team": "Mexico" },
  "MEX7": { "name": "Israel Reyes", "team": "Mexico" },
  "MEX8": { "name": "Diego Lainez", "team": "Mexico" },
  "MEX9": { "name": "Carlos Rodriguez", "team": "Mexico" },
  "MEX10": { "name": "Edson Alvarez", "team": "Mexico" },
  "MEX11": { "name": "Orbelin Pineda", "team": "Mexico" },
  "MEX12": { "name": "Marcel Ruiz", "team": "Mexico" },
  "MEX13": { "name": "Foto de Equipo", "team": "Mexico" },
  "MEX14": { "name": "Érick Sánchez", "team": "Mexico" },
  "MEX15": { "name": "Hirving Lozano", "team": "Mexico" },
  "MEX16": { "name": "Santiago Giménez", "team": "Mexico" },
  "MEX17": { "name": "Raúl Jiménez", "team": "Mexico" },
  "MEX18": { "name": "Alexis Vega", "team": "Mexico" },
  "MEX19": { "name": "Roberto Alvarado", "team": "Mexico" },
  "MEX20": { "name": "Cesar Huerta", "team": "Mexico" },

  // South Africa
  "RSA1": { "name": "Escudo (Emblem)", "team": "South Africa" },
  "RSA2": { "name": "Ronwen Williams", "team": "South Africa" },
  "RSA3": { "name": "Sipho Chaine", "team": "South Africa" },
  "RSA4": { "name": "Aubrey Modiba", "team": "South Africa" },
  "RSA5": { "name": "Samukele Kabini", "team": "South Africa" },
  "RSA6": { "name": "Mbekezeli Mbokazi", "team": "South Africa" },
  "RSA7": { "name": "Khulumani Ndamane", "team": "South Africa" },
  "RSA8": { "name": "Siyabonga Ngezana", "team": "South Africa" },
  "RSA9": { "name": "Khuliso Mudau", "team": "South Africa" },
  "RSA10": { "name": "Nkosinathi Sibisi", "team": "South Africa" },
  "RSA11": { "name": "Teboho Mokoena", "team": "South Africa" },
  "RSA12": { "name": "Thalente Mbatha", "team": "South Africa" },
  "RSA13": { "name": "Foto de Equipo", "team": "South Africa" },
  "RSA14": { "name": "Bathusi Aubaas", "team": "South Africa" },
  "RSA15": { "name": "Yaya Sithole", "team": "South Africa" },
  "RSA16": { "name": "Sipho Mbule", "team": "South Africa" },
  "RSA17": { "name": "Lyle Foster", "team": "South Africa" },
  "RSA18": { "name": "Iqraam Rayners", "team": "South Africa" },
  "RSA19": { "name": "Mohau Nkota", "team": "South Africa" },
  "RSA20": { "name": "Oswin Appollis", "team": "South Africa" },

  // South Korea
  "KOR1": { "name": "Escudo (Emblem)", "team": "South Korea" },
  "KOR2": { "name": "Hyeon-woo Jo", "team": "South Korea" },
  "KOR3": { "name": "Seung-Gyu Kim", "team": "South Korea" },
  "KOR4": { "name": "Min-jae Kim", "team": "South Korea" },
  "KOR5": { "name": "Yu-min Cho", "team": "South Korea" },
  "KOR6": { "name": "Young-woo Seol", "team": "South Korea" },
  "KOR7": { "name": "Han-beom Lee", "team": "South Korea" },
  "KOR8": { "name": "Tae-seok Lee", "team": "South Korea" },
  "KOR9": { "name": "Myung-jae Lee", "team": "South Korea" },
  "KOR10": { "name": "Jae-sung Lee", "team": "South Korea" },
  "KOR11": { "name": "In-beom Hwang", "team": "South Korea" },
  "KOR12": { "name": "Kang-in Lee", "team": "South Korea" },
  "KOR13": { "name": "Foto de Equipo", "team": "South Korea" },
  "KOR14": { "name": "Seung-ho Paik", "team": "South Korea" },
  "KOR15": { "name": "Jens Castrop", "team": "South Korea" },
  "KOR16": { "name": "Dongg-yeong Lee", "team": "South Korea" },
  "KOR17": { "name": "Gue-sung Cho", "team": "South Korea" },
  "KOR18": { "name": "Heung-min Son", "team": "South Korea" },
  "KOR19": { "name": "Hee-chan Hwang", "team": "South Korea" },
  "KOR20": { "name": "Hyeon-Gyu Oh", "team": "South Korea" },

  // Czechia
  "CZE1": { "name": "Escudo (Emblem)", "team": "Czechia" },
  "CZE2": { "name": "Matej Kovar", "team": "Czechia" },
  "CZE3": { "name": "Jindrich Stanek", "team": "Czechia" },
  "CZE4": { "name": "Ladislav Krejci", "team": "Czechia" },
  "CZE5": { "name": "Vladimir Coufal", "team": "Czechia" },
  "CZE6": { "name": "Jaroslav Zeleny", "team": "Czechia" },
  "CZE7": { "name": "Tomas Holes", "team": "Czechia" },
  "CZE8": { "name": "David Zima", "team": "Czechia" },
  "CZE9": { "name": "Michal Sadilek", "team": "Czechia" },
  "CZE10": { "name": "Lukas Provod", "team": "Czechia" },
  "CZE11": { "name": "Lukas Cerv", "team": "Czechia" },
  "CZE12": { "name": "Tomas Soucek", "team": "Czechia" },
  "CZE13": { "name": "Foto de Equipo", "team": "Czechia" },
  "CZE14": { "name": "Pavel Sulc", "team": "Czechia" },
  "CZE15": { "name": "Matej Vydra", "team": "Czechia" },
  "CZE16": { "name": "Vasil Kusej", "team": "Czechia" },
  "CZE17": { "name": "Tomas Chory", "team": "Czechia" },
  "CZE18": { "name": "Vaclav Cerny", "team": "Czechia" },
  "CZE19": { "name": "Adam Hlozek", "team": "Czechia" },
  "CZE20": { "name": "Patrik Schick", "team": "Czechia" },

  // Canada
  "CAN1": { "name": "Escudo (Emblem)", "team": "Canada" },
  "CAN2": { "name": "Dayne St.Clair", "team": "Canada" },
  "CAN3": { "name": "Alphonso Davies", "team": "Canada" },
  "CAN4": { "name": "Alistair Johnston", "team": "Canada" },
  "CAN5": { "name": "Samuel Adekugbe", "team": "Canada" },
  "CAN6": { "name": "Richie Laryea", "team": "Canada" },
  "CAN7": { "name": "Derek Cornelius", "team": "Canada" },
  "CAN8": { "name": "Moïse Bombito", "team": "Canada" },
  "CAN9": { "name": "Kamal Miller", "team": "Canada" },
  "CAN10": { "name": "Stephen Eustáquio", "team": "Canada" },
  "CAN11": { "name": "Ismaël Koné", "team": "Canada" },
  "CAN12": { "name": "Jonathan Osorio", "team": "Canada" },
  "CAN13": { "name": "Foto de Equipo", "team": "Canada" },
  "CAN14": { "name": "Jacob Shaffelburg", "team": "Canada" },
  "CAN15": { "name": "Mathieu Choinière", "team": "Canada" },
  "CAN16": { "name": "Niko Sigur", "team": "Canada" },
  "CAN17": { "name": "Tajon Buchanan", "team": "Canada" },
  "CAN18": { "name": "Liam Millar", "team": "Canada" },
  "CAN19": { "name": "Cyle Larin", "team": "Canada" },
  "CAN20": { "name": "Jonathan David", "team": "Canada" },

  // Bosnia and Herzegovina
  "BIH1": { "name": "Escudo (Emblem)", "team": "Bosnia and Herzegovina" },
  "BIH2": { "name": "Nikola Vasilj", "team": "Bosnia and Herzegovina" },
  "BIH3": { "name": "Amer Dedic", "team": "Bosnia and Herzegovina" },
  "BIH4": { "name": "Sead Kolasinac", "team": "Bosnia and Herzegovina" },
  "BIH5": { "name": "Tarik Muharemovic", "team": "Bosnia and Herzegovina" },
  "BIH6": { "name": "Nihad Mujakic", "team": "Bosnia and Herzegovina" },
  "BIH7": { "name": "Nikola Katic", "team": "Bosnia and Herzegovina" },
  "BIH8": { "name": "Amir Hadziahmetovic", "team": "Bosnia and Herzegovina" },
  "BIH9": { "name": "Benjamin Tahirovic", "team": "Bosnia and Herzegovina" },
  "BIH10": { "name": "Armin Gigovic", "team": "Bosnia and Herzegovina" },
  "BIH11": { "name": "Ivan Sunjic", "team": "Bosnia and Herzegovina" },
  "BIH12": { "name": "Ivan Basic", "team": "Bosnia and Herzegovina" },
  "BIH13": { "name": "Foto de Equipo", "team": "Bosnia and Herzegovina" },
  "BIH14": { "name": "Dzenis Burnic", "team": "Bosnia and Herzegovina" },
  "BIH15": { "name": "Esmir Bajraktarevic", "team": "Bosnia and Herzegovina" },
  "BIH16": { "name": "Amar Memic", "team": "Bosnia and Herzegovina" },
  "BIH17": { "name": "Ermedin Demirovic", "team": "Bosnia and Herzegovina" },
  "BIH18": { "name": "Edin Dzeko", "team": "Bosnia and Herzegovina" },
  "BIH19": { "name": "Samed Bazdar", "team": "Bosnia and Herzegovina" },
  "BIH20": { "name": "Haris Tabakovic", "team": "Bosnia and Herzegovina" },

  // Qatar
  "QAT1": { "name": "Escudo (Emblem)", "team": "Qatar" },
  "QAT2": { "name": "Meshaal Barsham", "team": "Qatar" },
  "QAT3": { "name": "Sultan Albrake", "team": "Qatar" },
  "QAT4": { "name": "Lucas Mendes", "team": "Qatar" },
  "QAT5": { "name": "Homam Ahmed", "team": "Qatar" },
  "QAT6": { "name": "Boualem Khoukhi", "team": "Qatar" },
  "QAT7": { "name": "Pedro Miguel", "team": "Qatar" },
  "QAT8": { "name": "Tarek Salman", "team": "Qatar" },
  "QAT9": { "name": "Mohamed Al-Mannai", "team": "Qatar" },
  "QAT10": { "name": "Karim Boudiaf", "team": "Qatar" },
  "QAT11": { "name": "Assim Madibo", "team": "Qatar" },
  "QAT12": { "name": "Ahmed Fatehi", "team": "Qatar" },
  "QAT13": { "name": "Foto de Equipo", "team": "Qatar" },
  "QAT14": { "name": "Mohammed Waad", "team": "Qatar" },
  "QAT15": { "name": "Abdulaziz Hatem", "team": "Qatar" },
  "QAT16": { "name": "Hassan Al-Haydos", "team": "Qatar" },
  "QAT17": { "name": "Edmilson Junior", "team": "Qatar" },
  "QAT18": { "name": "Akram Hassan Afif", "team": "Qatar" },
  "QAT19": { "name": "Ahmed Al Ganehi", "team": "Qatar" },
  "QAT20": { "name": "Almoez Ali", "team": "Qatar" },

  // Switzerland
  "SUI1": { "name": "Escudo (Emblem)", "team": "Switzerland" },
  "SUI2": { "name": "Gregor Kobel", "team": "Switzerland" },
  "SUI3": { "name": "Yvon Mvogo", "team": "Switzerland" },
  "SUI4": { "name": "Manuel Akanji", "team": "Switzerland" },
  "SUI5": { "name": "Ricardo Rodriguez", "team": "Switzerland" },
  "SUI6": { "name": "Nico Elvedi", "team": "Switzerland" },
  "SUI7": { "name": "Aurèle Amenda", "team": "Switzerland" },
  "SUI8": { "name": "Silvan Widmer", "team": "Switzerland" },
  "SUI9": { "name": "Granit Xhaka", "team": "Switzerland" },
  "SUI10": { "name": "Denis Zakaria", "team": "Switzerland" },
  "SUI11": { "name": "Remo Freuler", "team": "Switzerland" },
  "SUI12": { "name": "Fabian Rieder", "team": "Switzerland" },
  "SUI13": { "name": "Foto de Equipo", "team": "Switzerland" },
  "SUI14": { "name": "Ardon Jashari", "team": "Switzerland" },
  "SUI15": { "name": "Johan Manzambi", "team": "Switzerland" },
  "SUI16": { "name": "Michel Aebischer", "team": "Switzerland" },
  "SUI17": { "name": "Breel Embolo", "team": "Switzerland" },
  "SUI18": { "name": "Ruben Vargas", "team": "Switzerland" },
  "SUI19": { "name": "Dan Ndoye", "team": "Switzerland" },
  "SUI20": { "name": "Zeki Amdouni", "team": "Switzerland" },

  // Brazil
  "BRA1": { "name": "Escudo (Emblem)", "team": "Brazil" },
  "BRA2": { "name": "Alisson", "team": "Brazil" },
  "BRA3": { "name": "Bento", "team": "Brazil" },
  "BRA4": { "name": "Marquinhos", "team": "Brazil" },
  "BRA5": { "name": "Éder Militão", "team": "Brazil" },
  "BRA6": { "name": "Gabriel Magalhães", "team": "Brazil" },
  "BRA7": { "name": "Danilo", "team": "Brazil" },
  "BRA8": { "name": "Wesley", "team": "Brazil" },
  "BRA9": { "name": "Lucas Paquetá", "team": "Brazil" },
  "BRA10": { "name": "Casemiro", "team": "Brazil" },
  "BRA11": { "name": "Bruno Guimarães", "team": "Brazil" },
  "BRA12": { "name": "Luiz Henrique", "team": "Brazil" },
  "BRA13": { "name": "Foto de Equipo", "team": "Brazil" },
  "BRA14": { "name": "Vinicius Júnior", "team": "Brazil" },
  "BRA15": { "name": "Rodrygo", "team": "Brazil" },
  "BRA16": { "name": "João Pedro", "team": "Brazil" },
  "BRA17": { "name": "Matheus Cunha", "team": "Brazil" },
  "BRA18": { "name": "Gabriel Martinelli", "team": "Brazil" },
  "BRA19": { "name": "Raphinha", "team": "Brazil" },
  "BRA20": { "name": "Estévão", "team": "Brazil" },

  // Morocco
  "MAR1": { "name": "Escudo (Emblem)", "team": "Morocco" },
  "MAR2": { "name": "Yassine Bounou", "team": "Morocco" },
  "MAR3": { "name": "Munir El Kajoui", "team": "Morocco" },
  "MAR4": { "name": "Achraf Hakimi", "team": "Morocco" },
  "MAR5": { "name": "Noussair Mazraoui", "team": "Morocco" },
  "MAR6": { "name": "Nayef Aguerd", "team": "Morocco" },
  "MAR7": { "name": "Romain Saïss", "team": "Morocco" },
  "MAR8": { "name": "Jawad El Yamiq", "team": "Morocco" },
  "MAR9": { "name": "Adam Masina", "team": "Morocco" },
  "MAR10": { "name": "Sofyan Amrabat", "team": "Morocco" },
  "MAR11": { "name": "Azzedine Ounahi", "team": "Morocco" },
  "MAR12": { "name": "Eliesse Ben Seghir", "team": "Morocco" },
  "MAR13": { "name": "Foto de Equipo", "team": "Morocco" },
  "MAR14": { "name": "Bilal El Khannouss", "team": "Morocco" },
  "MAR15": { "name": "Ismael Saibari", "team": "Morocco" },
  "MAR16": { "name": "Youssef En-Nesyri", "team": "Morocco" },
  "MAR17": { "name": "Abde Ezzalzouli", "team": "Morocco" },
  "MAR18": { "name": "Soufiane Rahimi", "team": "Morocco" },
  "MAR19": { "name": "Brahim Diaz", "team": "Morocco" },
  "MAR20": { "name": "Ayoub El Kaabi", "team": "Morocco" },

  // Haiti
  "HAI1": { "name": "Escudo (Emblem)", "team": "Haiti" },
  "HAI2": { "name": "Johny Placide", "team": "Haiti" },
  "HAI3": { "name": "Carlens Arcus", "team": "Haiti" },
  "HAI4": { "name": "Martin Expérience", "team": "Haiti" },
  "HAI5": { "name": "Jean-Kevin Duverne", "team": "Haiti" },
  "HAI6": { "name": "Ricardo Adé", "team": "Haiti" },
  "HAI7": { "name": "Duke Lacroix", "team": "Haiti" },
  "HAI8": { "name": "Garven Metusala", "team": "Haiti" },
  "HAI9": { "name": "Hannes Delcroix", "team": "Haiti" },
  "HAI10": { "name": "Leverton Pierre", "team": "Haiti" },
  "HAI11": { "name": "Danley Jean Jacques", "team": "Haiti" },
  "HAI12": { "name": "Jean-Ricner Bellegarde", "team": "Haiti" },
  "HAI13": { "name": "Foto de Equipo", "team": "Haiti" },
  "HAI14": { "name": "Christopher Attys", "team": "Haiti" },
  "HAI15": { "name": "Derrick Etienne Jr", "team": "Haiti" },
  "HAI16": { "name": "Josue Casimir", "team": "Haiti" },
  "HAI17": { "name": "Ruben Providence", "team": "Haiti" },
  "HAI18": { "name": "Duckens Nazon", "team": "Haiti" },
  "HAI19": { "name": "Louicius Deedson", "team": "Haiti" },
  "HAI20": { "name": "Frantzdy Pierrot", "team": "Haiti" },

  // Scotland
  "SCO1": { "name": "Escudo (Emblem)", "team": "Scotland" },
  "SCO2": { "name": "Angus Gunn", "team": "Scotland" },
  "SCO3": { "name": "Jack Hendry", "team": "Scotland" },
  "SCO4": { "name": "Kieran Tierney", "team": "Scotland" },
  "SCO5": { "name": "Aaron Hickey", "team": "Scotland" },
  "SCO6": { "name": "Andrew Robertson", "team": "Scotland" },
  "SCO7": { "name": "Scott McKenna", "team": "Scotland" },
  "SCO8": { "name": "John Souttar", "team": "Scotland" },
  "SCO9": { "name": "Anthony Ralston", "team": "Scotland" },
  "SCO10": { "name": "Grant Hanley", "team": "Scotland" },
  "SCO11": { "name": "Scott McTominay", "team": "Scotland" },
  "SCO12": { "name": "Billy Gilmour", "team": "Scotland" },
  "SCO13": { "name": "Foto de Equipo", "team": "Scotland" },
  "SCO14": { "name": "Lewis Ferguson", "team": "Scotland" },
  "SCO15": { "name": "Ryan Christie", "team": "Scotland" },
  "SCO16": { "name": "Kenny McLean", "team": "Scotland" },
  "SCO17": { "name": "John McGinn", "team": "Scotland" },
  "SCO18": { "name": "Lyndon Dykes", "team": "Scotland" },
  "SCO19": { "name": "Che Adams", "team": "Scotland" },
  "SCO20": { "name": "Ben Gannon-Doak", "team": "Scotland" },

  // USA
  "USA1": { "name": "Escudo (Emblem)", "team": "USA" },
  "USA2": { "name": "Matt Freese", "team": "USA" },
  "USA3": { "name": "Chris Richards", "team": "USA" },
  "USA4": { "name": "Tim Ream", "team": "USA" },
  "USA5": { "name": "Mark McKenzie", "team": "USA" },
  "USA6": { "name": "Alex Freeman", "team": "USA" },
  "USA7": { "name": "Antonee Robinson", "team": "USA" },
  "USA8": { "name": "Tyler Adams", "team": "USA" },
  "USA9": { "name": "Tanner Tessmann", "team": "USA" },
  "USA10": { "name": "Weston McKenny", "team": "USA" },
  "USA11": { "name": "Christian Roldan", "team": "USA" },
  "USA12": { "name": "Timothy Weah", "team": "USA" },
  "USA13": { "name": "Foto de Equipo", "team": "USA" },
  "USA14": { "name": "Diego Luna", "team": "USA" },
  "USA15": { "name": "Malik Tillman", "team": "USA" },
  "USA16": { "name": "Christian Pulisic", "team": "USA" },
  "USA17": { "name": "Brenden Aaronson", "team": "USA" },
  "USA18": { "name": "Ricardo Pepi", "team": "USA" },
  "USA19": { "name": "Haji Wright", "team": "USA" },
  "USA20": { "name": "Folarin Balogun", "team": "USA" },

  // Paraguay
  "PAR1": { "name": "Escudo (Emblem)", "team": "Paraguay" },
  "PAR2": { "name": "Roberto Fernandez", "team": "Paraguay" },
  "PAR3": { "name": "Orlando Gill", "team": "Paraguay" },
  "PAR4": { "name": "Gustavo Gomez", "team": "Paraguay" },
  "PAR5": { "name": "Fabián Balbuena", "team": "Paraguay" },
  "PAR6": { "name": "Juan José Cáceres", "team": "Paraguay" },
  "PAR7": { "name": "Omar Alderete", "team": "Paraguay" },
  "PAR8": { "name": "Junior Alonso", "team": "Paraguay" },
  "PAR9": { "name": "Mathías Villasanti", "team": "Paraguay" },
  "PAR10": { "name": "Diego Gomez", "team": "Paraguay" },
  "PAR11": { "name": "Damián Bobadilla", "team": "Paraguay" },
  "PAR12": { "name": "Andres Cubas", "team": "Paraguay" },
  "PAR13": { "name": "Foto de Equipo", "team": "Paraguay" },
  "PAR14": { "name": "Matias Galarza Fonda", "team": "Paraguay" },
  "PAR15": { "name": "Julio Enciso", "team": "Paraguay" },
  "PAR16": { "name": "Alejandro Romero Gamarra", "team": "Paraguay" },
  "PAR17": { "name": "Miguel Almirón", "team": "Paraguay" },
  "PAR18": { "name": "Ramon Sosa", "team": "Paraguay" },
  "PAR19": { "name": "Angel Romero", "team": "Paraguay" },
  "PAR20": { "name": "Antonio Sanabria", "team": "Paraguay" },

  // Australia
  "AUS1": { "name": "Escudo (Emblem)", "team": "Australia" },
  "AUS2": { "name": "Mathew Ryan", "team": "Australia" },
  "AUS3": { "name": "Joe Gauci", "team": "Australia" },
  "AUS4": { "name": "Harry Souttar", "team": "Australia" },
  "AUS5": { "name": "Alessandro Circati", "team": "Australia" },
  "AUS6": { "name": "Jordan Bos", "team": "Australia" },
  "AUS7": { "name": "Aziz Behich", "team": "Australia" },
  "AUS8": { "name": "Cameron Burgess", "team": "Australia" },
  "AUS9": { "name": "Lewis Miller", "team": "Australia" },
  "AUS10": { "name": "Milos Degenek", "team": "Australia" },
  "AUS11": { "name": "Jackson Irvine", "team": "Australia" },
  "AUS12": { "name": "Riley McGree", "team": "Australia" },
  "AUS13": { "name": "Foto de Equipo", "team": "Australia" },
  "AUS14": { "name": "Aiden O'Neill", "team": "Australia" },
  "AUS15": { "name": "Connor Metcalfe", "team": "Australia" },
  "AUS16": { "name": "Patrick Yazbek", "team": "Australia" },
  "AUS17": { "name": "Craig Goodwin", "team": "Australia" },
  "AUS18": { "name": "Kusini Yengi", "team": "Australia" },
  "AUS19": { "name": "Nestory Irankunda", "team": "Australia" },
  "AUS20": { "name": "Mohamed Touré", "team": "Australia" },

  // Türkiye
  "TUR1": { "name": "Escudo (Emblem)", "team": "Türkiye" },
  "TUR2": { "name": "Ugurcan Cakir", "team": "Türkiye" },
  "TUR3": { "name": "Mert Muldur", "team": "Türkiye" },
  "TUR4": { "name": "Zeki Celik", "team": "Türkiye" },
  "TUR5": { "name": "Abdulkerim Bardakci", "team": "Türkiye" },
  "TUR6": { "name": "Caglar Soyuncu", "team": "Türkiye" },
  "TUR7": { "name": "Merih Demiral", "team": "Türkiye" },
  "TUR8": { "name": "Ferdi Kadioglu", "team": "Türkiye" },
  "TUR9": { "name": "Kaan Ayhan", "team": "Türkiye" },
  "TUR10": { "name": "Ismail Yuksek", "team": "Türkiye" },
  "TUR11": { "name": "Hakan Calhanoglu", "team": "Türkiye" },
  "TUR12": { "name": "Orkun Kokcu", "team": "Türkiye" },
  "TUR13": { "name": "Foto de Equipo", "team": "Türkiye" },
  "TUR14": { "name": "Arda Guler", "team": "Türkiye" },
  "TUR15": { "name": "Irfan Can Kahveci", "team": "Türkiye" },
  "TUR16": { "name": "Yunus Akgun", "team": "Türkiye" },
  "TUR17": { "name": "Can Uzun", "team": "Türkiye" },
  "TUR18": { "name": "Baris Alper Yilmaz", "team": "Türkiye" },
  "TUR19": { "name": "Kerem Akturkoglu", "team": "Türkiye" },
  "TUR20": { "name": "Kenan Yildiz", "team": "Türkiye" },

  // Germany
  "GER1": { "name": "Escudo (Emblem)", "team": "Germany" },
  "GER2": { "name": "Marc-André ter Stegen", "team": "Germany" },
  "GER3": { "name": "Jonathan Tah", "team": "Germany" },
  "GER4": { "name": "David Raum", "team": "Germany" },
  "GER5": { "name": "Nico Schlotterbeck", "team": "Germany" },
  "GER6": { "name": "Antonio Rüdiger", "team": "Germany" },
  "GER7": { "name": "Waldemar Anton", "team": "Germany" },
  "GER8": { "name": "Ridle Baku", "team": "Germany" },
  "GER9": { "name": "Maximilian Mittelstadt", "team": "Germany" },
  "GER10": { "name": "Joshua Kimmich", "team": "Germany" },
  "GER11": { "name": "Florian Wirtz", "team": "Germany" },
  "GER12": { "name": "Felix Nmecha", "team": "Germany" },
  "GER13": { "name": "Foto de Equipo", "team": "Germany" },
  "GER14": { "name": "Leon Goretzka", "team": "Germany" },
  "GER15": { "name": "Jamal Musiala", "team": "Germany" },
  "GER16": { "name": "Serge Gnabry", "team": "Germany" },
  "GER17": { "name": "Kai Havertz", "team": "Germany" },
  "GER18": { "name": "Leroy Sane", "team": "Germany" },
  "GER19": { "name": "Karim Adeyemi", "team": "Germany" },
  "GER20": { "name": "Nick Woltemade", "team": "Germany" },

  // Curaçao
  "CUW1": { "name": "Escudo (Emblem)", "team": "Curaçao" },
  "CUW2": { "name": "Eloy Room", "team": "Curaçao" },
  "CUW3": { "name": "Armando Obispo", "team": "Curaçao" },
  "CUW4": { "name": "Sherel Floranus", "team": "Curaçao" },
  "CUW5": { "name": "Jurien Gaari", "team": "Curaçao" },
  "CUW6": { "name": "Joshua Brenet", "team": "Curaçao" },
  "CUW7": { "name": "Roshon Van Eijma", "team": "Curaçao" },
  "CUW8": { "name": "Shurandy Sambo", "team": "Curaçao" },
  "CUW9": { "name": "Livano Comenencia", "team": "Curaçao" },
  "CUW10": { "name": "Godfried Roemeratoe", "team": "Curaçao" },
  "CUW11": { "name": "Juninho Bacuna", "team": "Curaçao" },
  "CUW12": { "name": "Leandro Bacuna", "team": "Curaçao" },
  "CUW13": { "name": "Foto de Equipo", "team": "Curaçao" },
  "CUW14": { "name": "Tahith Chong", "team": "Curaçao" },
  "CUW15": { "name": "Kenji Gorre", "team": "Curaçao" },
  "CUW16": { "name": "Jearl Margaritha", "team": "Curaçao" },
  "CUW17": { "name": "Jurgen Locadia", "team": "Curaçao" },
  "CUW18": { "name": "Jeremy Antonisse", "team": "Curaçao" },
  "CUW19": { "name": "Gervane Kastaneer", "team": "Curaçao" },
  "CUW20": { "name": "Sontje Hansen", "team": "Curaçao" },

  // Ivory Coast
  "CIV1": { "name": "Escudo (Emblem)", "team": "Ivory Coast" },
  "CIV2": { "name": "Yahia Fofana", "team": "Ivory Coast" },
  "CIV3": { "name": "Ghislain Konan", "team": "Ivory Coast" },
  "CIV4": { "name": "Wilfried Singo", "team": "Ivory Coast" },
  "CIV5": { "name": "Odilon Kossounou", "team": "Ivory Coast" },
  "CIV6": { "name": "Evan Ndicka", "team": "Ivory Coast" },
  "CIV7": { "name": "Willy Boly", "team": "Ivory Coast" },
  "CIV8": { "name": "Emmanuel Agbadou", "team": "Ivory Coast" },
  "CIV9": { "name": "Ousmane Diomande", "team": "Ivory Coast" },
  "CIV10": { "name": "Franck Kessie", "team": "Ivory Coast" },
  "CIV11": { "name": "Seko Fofana", "team": "Ivory Coast" },
  "CIV12": { "name": "Ibrahim Sangare", "team": "Ivory Coast" },
  "CIV13": { "name": "Foto de Equipo", "team": "Ivory Coast" },
  "CIV14": { "name": "Jean-Philippe Gbamin", "team": "Ivory Coast" },
  "CIV15": { "name": "Amad Diallo", "team": "Ivory Coast" },
  "CIV16": { "name": "Sébastien Haller", "team": "Ivory Coast" },
  "CIV17": { "name": "Simon Adingra", "team": "Ivory Coast" },
  "CIV18": { "name": "Yan Diomande", "team": "Ivory Coast" },
  "CIV19": { "name": "Evann Guessand", "team": "Ivory Coast" },
  "CIV20": { "name": "Oumar Diakite", "team": "Ivory Coast" },

  // Ecuador
  "ECU1": { "name": "Escudo (Emblem)", "team": "Ecuador" },
  "ECU2": { "name": "Hernán Galíndez", "team": "Ecuador" },
  "ECU3": { "name": "Gonzalo Valle", "team": "Ecuador" },
  "ECU4": { "name": "Piero Hincapié", "team": "Ecuador" },
  "ECU5": { "name": "Pervis Estupiñán", "team": "Ecuador" },
  "ECU6": { "name": "Willian Pacho", "team": "Ecuador" },
  "ECU7": { "name": "Ángelo Preciado", "team": "Ecuador" },
  "ECU8": { "name": "Joel Ordóñez", "team": "Ecuador" },
  "ECU9": { "name": "Moises Caicedo", "team": "Ecuador" },
  "ECU10": { "name": "Alan Franco", "team": "Ecuador" },
  "ECU11": { "name": "Kendry Paez", "team": "Ecuador" },
  "ECU12": { "name": "Pedro Vite", "team": "Ecuador" },
  "ECU13": { "name": "Foto de Equipo", "team": "Ecuador" },
  "ECU14": { "name": "John Yeboah", "team": "Ecuador" },
  "ECU15": { "name": "Leonardo Campana", "team": "Ecuador" },
  "ECU16": { "name": "Gonzalo Plata", "team": "Ecuador" },
  "ECU17": { "name": "Nilson Angulo", "team": "Ecuador" },
  "ECU18": { "name": "Alan Minda", "team": "Ecuador" },
  "ECU19": { "name": "Kevin Rodriguez", "team": "Ecuador" },
  "ECU20": { "name": "Enner Valencia", "team": "Ecuador" },

  // Netherlands
  "NED1": { "name": "Escudo (Emblem)", "team": "Netherlands" },
  "NED2": { "name": "Bart Verbruggen", "team": "Netherlands" },
  "NED3": { "name": "Virgil van Dijk", "team": "Netherlands" },
  "NED4": { "name": "Micky van de Ven", "team": "Netherlands" },
  "NED5": { "name": "Jurrien Timber", "team": "Netherlands" },
  "NED6": { "name": "Denzel Dumfries", "team": "Netherlands" },
  "NED7": { "name": "Nathan Aké", "team": "Netherlands" },
  "NED8": { "name": "Jeremie Frimpong", "team": "Netherlands" },
  "NED9": { "name": "Jan Paul van Hecke", "team": "Netherlands" },
  "NED10": { "name": "Tijjani Reijnders", "team": "Netherlands" },
  "NED11": { "name": "Ryan Gravenberch", "team": "Netherlands" },
  "NED12": { "name": "Teun Koopmeiners", "team": "Netherlands" },
  "NED13": { "name": "Foto de Equipo", "team": "Netherlands" },
  "NED14": { "name": "Frenkie de Jong", "team": "Netherlands" },
  "NED15": { "name": "Xavi Simons", "team": "Netherlands" },
  "NED16": { "name": "Justin Kluivert", "team": "Netherlands" },
  "NED17": { "name": "Memphis Depay", "team": "Netherlands" },
  "NED18": { "name": "Donyell Malen", "team": "Netherlands" },
  "NED19": { "name": "Wout Weghorst", "team": "Netherlands" },
  "NED20": { "name": "Cody Gakpo", "team": "Netherlands" },

  // Japan
  "JPN1": { "name": "Escudo (Emblem)", "team": "Japan" },
  "JPN2": { "name": "Zion Suzuki", "team": "Japan" },
  "JPN3": { "name": "Henry Heroki Mochizuki", "team": "Japan" },
  "JPN4": { "name": "Ayumu Seko", "team": "Japan" },
  "JPN5": { "name": "Junnosuke Suzuki", "team": "Japan" },
  "JPN6": { "name": "Shogo Taniguchi", "team": "Japan" },
  "JPN7": { "name": "Tsuyoshi Watanabe", "team": "Japan" },
  "JPN8": { "name": "Kaishu Sano", "team": "Japan" },
  "JPN9": { "name": "Yuki Soma", "team": "Japan" },
  "JPN10": { "name": "Ao Tanaka", "team": "Japan" },
  "JPN11": { "name": "Daichi Kamada", "team": "Japan" },
  "JPN12": { "name": "Takefusa Kubo", "team": "Japan" },
  "JPN13": { "name": "Foto de Equipo", "team": "Japan" },
  "JPN14": { "name": "Ritsu Doan", "team": "Japan" },
  "JPN15": { "name": "Keito Nakamura", "team": "Japan" },
  "JPN16": { "name": "Takumi Minamino", "team": "Japan" },
  "JPN17": { "name": "Shuto Machino", "team": "Japan" },
  "JPN18": { "name": "Junya Ito", "team": "Japan" },
  "JPN19": { "name": "Koki Ogawa", "team": "Japan" },
  "JPN20": { "name": "Ayase Ueda", "team": "Japan" },

  // Sweden
  "SWE1": { "name": "Escudo (Emblem)", "team": "Sweden" },
  "SWE2": { "name": "Victor Johansson", "team": "Sweden" },
  "SWE3": { "name": "Isak Hien", "team": "Sweden" },
  "SWE4": { "name": "Gabriel Gudmundsson", "team": "Sweden" },
  "SWE5": { "name": "Emil Holm", "team": "Sweden" },
  "SWE6": { "name": "Victor Nilsson Lindelöf", "team": "Sweden" },
  "SWE7": { "name": "Gustaf Lagerbielke", "team": "Sweden" },
  "SWE8": { "name": "Lucas Bergvall", "team": "Sweden" },
  "SWE9": { "name": "Hugo Larsson", "team": "Sweden" },
  "SWE10": { "name": "Jesper Karlström", "team": "Sweden" },
  "SWE11": { "name": "Yasin Ayari", "team": "Sweden" },
  "SWE12": { "name": "Mattias Svanberg", "team": "Sweden" },
  "SWE13": { "name": "Foto de Equipo", "team": "Sweden" },
  "SWE14": { "name": "Daniel Svensson", "team": "Sweden" },
  "SWE15": { "name": "Ken Sema", "team": "Sweden" },
  "SWE16": { "name": "Roony Bardghji", "team": "Sweden" },
  "SWE17": { "name": "Dejan Kulusevski", "team": "Sweden" },
  "SWE18": { "name": "Anthony Elanga", "team": "Sweden" },
  "SWE19": { "name": "Alexander Isak", "team": "Sweden" },
  "SWE20": { "name": "Viktor Gyökeres", "team": "Sweden" },

  // Tunisia
  "TUN1": { "name": "Escudo (Emblem)", "team": "Tunisia" },
  "TUN2": { "name": "Bechir Ben Said", "team": "Tunisia" },
  "TUN3": { "name": "Aymen Dahmen", "team": "Tunisia" },
  "TUN4": { "name": "Yan Valery", "team": "Tunisia" },
  "TUN5": { "name": "Montassar Talbi", "team": "Tunisia" },
  "TUN6": { "name": "Yassine Meriah", "team": "Tunisia" },
  "TUN7": { "name": "Ali Abdi", "team": "Tunisia" },
  "TUN8": { "name": "Dylan Bronn", "team": "Tunisia" },
  "TUN9": { "name": "Ellyes Skhiri", "team": "Tunisia" },
  "TUN10": { "name": "Aissa Laidouni", "team": "Tunisia" },
  "TUN11": { "name": "Ferjani Sassi", "team": "Tunisia" },
  "TUN12": { "name": "Mohamed Ali Ben Romdhane", "team": "Tunisia" },
  "TUN13": { "name": "Foto de Equipo", "team": "Tunisia" },
  "TUN14": { "name": "Hannibal Mejbri", "team": "Tunisia" },
  "TUN15": { "name": "Elias Achouri", "team": "Tunisia" },
  "TUN16": { "name": "Elias Saad", "team": "Tunisia" },
  "TUN17": { "name": "Hazem Mastouri", "team": "Tunisia" },
  "TUN18": { "name": "Ismael Gharbi", "team": "Tunisia" },
  "TUN19": { "name": "Sayfallah Ltaief", "team": "Tunisia" },
  "TUN20": { "name": "Naim Sliti", "team": "Tunisia" },

  // Belgium
  "BEL1": { "name": "Escudo (Emblem)", "team": "Belgium" },
  "BEL2": { "name": "Thibaut Courtois", "team": "Belgium" },
  "BEL3": { "name": "Arthur Theate", "team": "Belgium" },
  "BEL4": { "name": "Timothy Castagne", "team": "Belgium" },
  "BEL5": { "name": "Zeno Debast", "team": "Belgium" },
  "BEL6": { "name": "Brandon Mechele", "team": "Belgium" },
  "BEL7": { "name": "Maxim De Cuyper", "team": "Belgium" },
  "BEL8": { "name": "Thomas Meunier", "team": "Belgium" },
  "BEL9": { "name": "Youri Tielemans", "team": "Belgium" },
  "BEL10": { "name": "Amadou Onana", "team": "Belgium" },
  "BEL11": { "name": "Nicolas Raskin", "team": "Belgium" },
  "BEL12": { "name": "Alexis Saelemaekers", "team": "Belgium" },
  "BEL13": { "name": "Foto de Equipo", "team": "Belgium" },
  "BEL14": { "name": "Hans Vanaken", "team": "Belgium" },
  "BEL15": { "name": "Kevin De Bruyne", "team": "Belgium" },
  "BEL16": { "name": "Jérémy Doku", "team": "Belgium" },
  "BEL17": { "name": "Charles De Ketelaere", "team": "Belgium" },
  "BEL18": { "name": "Leandro Trossard", "team": "Belgium" },
  "BEL19": { "name": "Loïs Openda", "team": "Belgium" },
  "BEL20": { "name": "Romelu Lukaku", "team": "Belgium" },

  // Egypt
  "EGY1": { "name": "Escudo (Emblem)", "team": "Egypt" },
  "EGY2": { "name": "Mohamed El Shenawy", "team": "Egypt" },
  "EGY3": { "name": "Mohamed Hany", "team": "Egypt" },
  "EGY4": { "name": "Mohamed Hamdy", "team": "Egypt" },
  "EGY5": { "name": "Yasser Ibrahim", "team": "Egypt" },
  "EGY6": { "name": "Khaled Sobhi", "team": "Egypt" },
  "EGY7": { "name": "Ramy Rabia", "team": "Egypt" },
  "EGY8": { "name": "Hossam Abdelmaguid", "team": "Egypt" },
  "EGY9": { "name": "Ahmed Fatouh", "team": "Egypt" },
  "EGY10": { "name": "Marwan Attia", "team": "Egypt" },
  "EGY11": { "name": "Zizo", "team": "Egypt" },
  "EGY12": { "name": "Hamdy Fathy", "team": "Egypt" },
  "EGY13": { "name": "Foto de Equipo", "team": "Egypt" },
  "EGY14": { "name": "Mohamed Lasheen", "team": "Egypt" },
  "EGY15": { "name": "Emam Ashour", "team": "Egypt" },
  "EGY16": { "name": "Osama Faisal", "team": "Egypt" },
  "EGY17": { "name": "Mohamed Salah", "team": "Egypt" },
  "EGY18": { "name": "Mostafa Mohamed", "team": "Egypt" },
  "EGY19": { "name": "Trezeguet", "team": "Egypt" },
  "EGY20": { "name": "Omar Marmoush", "team": "Egypt" },

  // Iran
  "IRN1": { "name": "Escudo (Emblem)", "team": "Iran" },
  "IRN2": { "name": "Alireza Beiranvand", "team": "Iran" },
  "IRN3": { "name": "Morteza Pouraliganji", "team": "Iran" },
  "IRN4": { "name": "Ehsan Hajsafi", "team": "Iran" },
  "IRN5": { "name": "Milad Mohammadi", "team": "Iran" },
  "IRN6": { "name": "Shojae Khalilzadeh", "team": "Iran" },
  "IRN7": { "name": "Ramin Rezaeian", "team": "Iran" },
  "IRN8": { "name": "Hossein Kanaani", "team": "Iran" },
  "IRN9": { "name": "Sadegh Moharrami", "team": "Iran" },
  "IRN10": { "name": "Saleh Hardani", "team": "Iran" },
  "IRN11": { "name": "Saeed Ezatolahi", "team": "Iran" },
  "IRN12": { "name": "Saman Ghoddos", "team": "Iran" },
  "IRN13": { "name": "Foto de Equipo", "team": "Iran" },
  "IRN14": { "name": "Omid Noorafkan", "team": "Iran" },
  "IRN15": { "name": "Roozbeh Cheshmi", "team": "Iran" },
  "IRN16": { "name": "Mohammad Mohebi", "team": "Iran" },
  "IRN17": { "name": "Sardar Azmoun", "team": "Iran" },
  "IRN18": { "name": "Mehdi Taremi", "team": "Iran" },
  "IRN19": { "name": "Alireza Jahanbakhsh", "team": "Iran" },
  "IRN20": { "name": "Ali Gholizadeh", "team": "Iran" },

  // New Zealand
  "NZL1": { "name": "Escudo (Emblem)", "team": "New Zealand" },
  "NZL2": { "name": "Max Crocombe", "team": "New Zealand" },
  "NZL3": { "name": "Alex Paulsen", "team": "New Zealand" },
  "NZL4": { "name": "Michael Boxall", "team": "New Zealand" },
  "NZL5": { "name": "Liberato Cacace", "team": "New Zealand" },
  "NZL6": { "name": "Tim Payne", "team": "New Zealand" },
  "NZL7": { "name": "Tyler Bindon", "team": "New Zealand" },
  "NZL8": { "name": "Francis de Vries", "team": "New Zealand" },
  "NZL9": { "name": "Finn Surman", "team": "New Zealand" },
  "NZL10": { "name": "Joe Bell", "team": "New Zealand" },
  "NZL11": { "name": "Sarpreet Singh", "team": "New Zealand" },
  "NZL12": { "name": "Ryan Thomas", "team": "New Zealand" },
  "NZL13": { "name": "Foto de Equipo", "team": "New Zealand" },
  "NZL14": { "name": "Matthew Garbett", "team": "New Zealand" },
  "NZL15": { "name": "Marko Stamenić", "team": "New Zealand" },
  "NZL16": { "name": "Ben Old", "team": "New Zealand" },
  "NZL17": { "name": "Chris Wood", "team": "New Zealand" },
  "NZL18": { "name": "Elijah Just", "team": "New Zealand" },
  "NZL19": { "name": "Callum McCowatt", "team": "New Zealand" },
  "NZL20": { "name": "Kosta Barbarouses", "team": "New Zealand" },

  // Spain
  "ESP1": { "name": "Escudo (Emblem)", "team": "Spain" },
  "ESP2": { "name": "Unai Simon", "team": "Spain" },
  "ESP3": { "name": "Robin Le Normand", "team": "Spain" },
  "ESP4": { "name": "Aymeric Laporte", "team": "Spain" },
  "ESP5": { "name": "Dean Huijsen", "team": "Spain" },
  "ESP6": { "name": "Pedro Porro", "team": "Spain" },
  "ESP7": { "name": "Dani Carvajal", "team": "Spain" },
  "ESP8": { "name": "Marc Cucurella", "team": "Spain" },
  "ESP9": { "name": "Martín Zubimendi", "team": "Spain" },
  "ESP10": { "name": "Rodri", "team": "Spain" },
  "ESP11": { "name": "Pedri", "team": "Spain" },
  "ESP12": { "name": "Fabian Ruiz", "team": "Spain" },
  "ESP13": { "name": "Foto de Equipo", "team": "Spain" },
  "ESP14": { "name": "Mikel Merino", "team": "Spain" },
  "ESP15": { "name": "Lamine Yamal", "team": "Spain" },
  "ESP16": { "name": "Dani Olmo", "team": "Spain" },
  "ESP17": { "name": "Nico Williams", "team": "Spain" },
  "ESP18": { "name": "Ferran Torres", "team": "Spain" },
  "ESP19": { "name": "Álvaro Morata", "team": "Spain" },
  "ESP20": { "name": "Mikel Oyarzabal", "team": "Spain" },

  // Cape Verde
  "CPV1": { "name": "Escudo (Emblem)", "team": "Cape Verde" },
  "CPV2": { "name": "Vozinha", "team": "Cape Verde" },
  "CPV3": { "name": "Logan Costa", "team": "Cape Verde" },
  "CPV4": { "name": "Pico", "team": "Cape Verde" },
  "CPV5": { "name": "Diney", "team": "Cape Verde" },
  "CPV6": { "name": "Steven Moreira", "team": "Cape Verde" },
  "CPV7": { "name": "Wagner Pina", "team": "Cape Verde" },
  "CPV8": { "name": "Joao Paulo", "team": "Cape Verde" },
  "CPV9": { "name": "Yannick Semedo", "team": "Cape Verde" },
  "CPV10": { "name": "Kevin Pina", "team": "Cape Verde" },
  "CPV11": { "name": "Patrick Andrade", "team": "Cape Verde" },
  "CPV12": { "name": "Jamiro Monteiro", "team": "Cape Verde" },
  "CPV13": { "name": "Foto de Equipo", "team": "Cape Verde" },
  "CPV14": { "name": "Deroy Duarte", "team": "Cape Verde" },
  "CPV15": { "name": "Garry Rodrigues", "team": "Cape Verde" },
  "CPV16": { "name": "Jovane Cabral", "team": "Cape Verde" },
  "CPV17": { "name": "Ryan Mendes", "team": "Cape Verde" },
  "CPV18": { "name": "Dailon Livramento", "team": "Cape Verde" },
  "CPV19": { "name": "Willy Semedo", "team": "Cape Verde" },
  "CPV20": { "name": "Bebe", "team": "Cape Verde" },

  // Saudi Arabia
  "KSA1": { "name": "Escudo (Emblem)", "team": "Saudi Arabia" },
  "KSA2": { "name": "Nawaf Alaqidi", "team": "Saudi Arabia" },
  "KSA3": { "name": "Abdulrahman Al-Sanbi", "team": "Saudi Arabia" },
  "KSA4": { "name": "Saud Abdulhamid", "team": "Saudi Arabia" },
  "KSA5": { "name": "Nawaf Bouwashl", "team": "Saudi Arabia" },
  "KSA6": { "name": "Jihad Thakri", "team": "Saudi Arabia" },
  "KSA7": { "name": "Moteb Al-Harbi", "team": "Saudi Arabia" },
  "KSA8": { "name": "Hassan Altambakti", "team": "Saudi Arabia" },
  "KSA9": { "name": "Musab Aljuwayr", "team": "Saudi Arabia" },
  "KSA10": { "name": "Ziyad Aljohani", "team": "Saudi Arabia" },
  "KSA11": { "name": "Abdullah Alkhaibari", "team": "Saudi Arabia" },
  "KSA12": { "name": "Nasser Aldawsari", "team": "Saudi Arabia" },
  "KSA13": { "name": "Foto de Equipo", "team": "Saudi Arabia" },
  "KSA14": { "name": "Saleh Abu Alshamat", "team": "Saudi Arabia" },
  "KSA15": { "name": "Marwan Alsahafi", "team": "Saudi Arabia" },
  "KSA16": { "name": "Salem Aldawsari", "team": "Saudi Arabia" },
  "KSA17": { "name": "Abdulrahman Al-Aboud", "team": "Saudi Arabia" },
  "KSA18": { "name": "Feras Akbrikan", "team": "Saudi Arabia" },
  "KSA19": { "name": "Saleh Alshehri", "team": "Saudi Arabia" },
  "KSA20": { "name": "Abdullah Al-Hamdan", "team": "Saudi Arabia" },

  // Uruguay
  "URU1": { "name": "Escudo (Emblem)", "team": "Uruguay" },
  "URU2": { "name": "Sergio Rochet", "team": "Uruguay" },
  "URU3": { "name": "Santiago Mele", "team": "Uruguay" },
  "URU4": { "name": "Ronald Araujo", "team": "Uruguay" },
  "URU5": { "name": "José María Giménez", "team": "Uruguay" },
  "URU6": { "name": "Sebastian Caceres", "team": "Uruguay" },
  "URU7": { "name": "Mathias Olivera", "team": "Uruguay" },
  "URU8": { "name": "Guillermo Varela", "team": "Uruguay" },
  "URU9": { "name": "Nahitan Nandez", "team": "Uruguay" },
  "URU10": { "name": "Federico Valverde", "team": "Uruguay" },
  "URU11": { "name": "Giorgian De Arrascaeta", "team": "Uruguay" },
  "URU12": { "name": "Rodrigo Bentancur", "team": "Uruguay" },
  "URU13": { "name": "Foto de Equipo", "team": "Uruguay" },
  "URU14": { "name": "Manuel Ugarte", "team": "Uruguay" },
  "URU15": { "name": "Nicolás de la Cruz", "team": "Uruguay" },
  "URU16": { "name": "Maxi Araujo", "team": "Uruguay" },
  "URU17": { "name": "Darwin Núñez", "team": "Uruguay" },
  "URU18": { "name": "Federico Viñas", "team": "Uruguay" },
  "URU19": { "name": "Rodrigo Aguirre", "team": "Uruguay" },
  "URU20": { "name": "Facundo Pellistri", "team": "Uruguay" },

  // France
  "FRA1": { "name": "Escudo (Emblem)", "team": "France" },
  "FRA2": { "name": "Mike Maignan", "team": "France" },
  "FRA3": { "name": "Theo Hernandez", "team": "France" },
  "FRA4": { "name": "William Saliba", "team": "France" },
  "FRA5": { "name": "Jules Kounde", "team": "France" },
  "FRA6": { "name": "Ibrahima Konate", "team": "France" },
  "FRA7": { "name": "Dayot Upamecano", "team": "France" },
  "FRA8": { "name": "Lucas Digne", "team": "France" },
  "FRA9": { "name": "Aurélien Tchouaméni", "team": "France" },
  "FRA10": { "name": "Eduardo Camavinga", "team": "France" },
  "FRA11": { "name": "Manu Kone", "team": "France" },
  "FRA12": { "name": "Adrien Rabiot", "team": "France" },
  "FRA13": { "name": "Foto de Equipo", "team": "France" },
  "FRA14": { "name": "Michael Olise", "team": "France" },
  "FRA15": { "name": "Ousmane Dembele", "team": "France" },
  "FRA16": { "name": "Bradley Barcola", "team": "France" },
  "FRA17": { "name": "Désiré Doué", "team": "France" },
  "FRA18": { "name": "Kingsley Coman", "team": "France" },
  "FRA19": { "name": "Hugo Ekitike", "team": "France" },
  "FRA20": { "name": "Kylian Mbappe", "team": "France" },

  // Senegal
  "SEN1": { "name": "Escudo (Emblem)", "team": "Senegal" },
  "SEN2": { "name": "Édouard Mendy", "team": "Senegal" },
  "SEN3": { "name": "Yehvann Diouf", "team": "Senegal" },
  "SEN4": { "name": "Moussa Niakhaté", "team": "Senegal" },
  "SEN5": { "name": "Abdoulaye Seck", "team": "Senegal" },
  "SEN6": { "name": "Ismail Jakobs", "team": "Senegal" },
  "SEN7": { "name": "El Hadji Malick Diouf", "team": "Senegal" },
  "SEN8": { "name": "Kalidou Koulibaly", "team": "Senegal" },
  "SEN9": { "name": "Idrissa Gana Gueye", "team": "Senegal" },
  "SEN10": { "name": "Pape Matar Sarr", "team": "Senegal" },
  "SEN11": { "name": "Pape Gueye", "team": "Senegal" },
  "SEN12": { "name": "Habib Diarra", "team": "Senegal" },
  "SEN13": { "name": "Foto de Equipo", "team": "Senegal" },
  "SEN14": { "name": "Lamine Camara", "team": "Senegal" },
  "SEN15": { "name": "Sadio Mane", "team": "Senegal" },
  "SEN16": { "name": "Ismaïla Sarr", "team": "Senegal" },
  "SEN17": { "name": "Boulaye Dia", "team": "Senegal" },
  "SEN18": { "name": "Iliman Ndiaye", "team": "Senegal" },
  "SEN19": { "name": "Nicolas Jackson", "team": "Senegal" },
  "SEN20": { "name": "Krepin Diatta", "team": "Senegal" },

  // Iraq
  "IRQ1": { "name": "Escudo (Emblem)", "team": "Iraq" },
  "IRQ2": { "name": "Jalal Hassan", "team": "Iraq" },
  "IRQ3": { "name": "Rebin Sulaka", "team": "Iraq" },
  "IRQ4": { "name": "Hussein Ali", "team": "Iraq" },
  "IRQ5": { "name": "Akam Hashem", "team": "Iraq" },
  "IRQ6": { "name": "Merchas Doski", "team": "Iraq" },
  "IRQ7": { "name": "Zaid Tahseen", "team": "Iraq" },
  "IRQ8": { "name": "Manaf Younis", "team": "Iraq" },
  "IRQ9": { "name": "Zidane Iqbal", "team": "Iraq" },
  "IRQ10": { "name": "Amir Al-Ammari", "team": "Iraq" },
  "IRQ11": { "name": "Ibrahim Bavesh", "team": "Iraq" },
  "IRQ12": { "name": "Ali Jasim", "team": "Iraq" },
  "IRQ13": { "name": "Foto de Equipo", "team": "Iraq" },
  "IRQ14": { "name": "Youssef Amyn", "team": "Iraq" },
  "IRQ15": { "name": "Aimar Sher", "team": "Iraq" },
  "IRQ16": { "name": "Marko Farji", "team": "Iraq" },
  "IRQ17": { "name": "Osama Rashid", "team": "Iraq" },
  "IRQ18": { "name": "Ali Al-Hamadi", "team": "Iraq" },
  "IRQ19": { "name": "Aymen Hussein", "team": "Iraq" },
  "IRQ20": { "name": "Mohanad Ali", "team": "Iraq" },

  // Norway
  "NOR1": { "name": "Escudo (Emblem)", "team": "Norway" },
  "NOR2": { "name": "Orjan Nyland", "team": "Norway" },
  "NOR3": { "name": "Julian Ryerson", "team": "Norway" },
  "NOR4": { "name": "Leo Ostigård", "team": "Norway" },
  "NOR5": { "name": "Kristoffer Vassbakk Ajer", "team": "Norway" },
  "NOR6": { "name": "Marcus Holmgren Pedersen", "team": "Norway" },
  "NOR7": { "name": "David Møller Wolfe", "team": "Norway" },
  "NOR8": { "name": "Torbjørn Heggem", "team": "Norway" },
  "NOR9": { "name": "Morten Thorsby", "team": "Norway" },
  "NOR10": { "name": "Martin Ødegaard", "team": "Norway" },
  "NOR11": { "name": "Sander Berge", "team": "Norway" },
  "NOR12": { "name": "Andreas Schjelderup", "team": "Norway" },
  "NOR13": { "name": "Foto de Equipo", "team": "Norway" },
  "NOR14": { "name": "Patrick Berg", "team": "Norway" },
  "NOR15": { "name": "Erling Haaland", "team": "Norway" },
  "NOR16": { "name": "Alexander Sørloth", "team": "Norway" },
  "NOR17": { "name": "Aron Dønnum", "team": "Norway" },
  "NOR18": { "name": "Jorgen Strand Larsen", "team": "Norway" },
  "NOR19": { "name": "Antonio Nusa", "team": "Norway" },
  "NOR20": { "name": "Oscar Bobb", "team": "Norway" },

  // Argentina
  "ARG1": { "name": "Escudo (Emblem)", "team": "Argentina" },
  "ARG2": { "name": "Emiliano Martinez", "team": "Argentina" },
  "ARG3": { "name": "Nahuel Molina", "team": "Argentina" },
  "ARG4": { "name": "Cristian Romero", "team": "Argentina" },
  "ARG5": { "name": "Nicolas Otamendi", "team": "Argentina" },
  "ARG6": { "name": "Nicolas Tagliafico", "team": "Argentina" },
  "ARG7": { "name": "Leonardo Balerdi", "team": "Argentina" },
  "ARG8": { "name": "Enzo Fernandez", "team": "Argentina" },
  "ARG9": { "name": "Alexis Mac Allister", "team": "Argentina" },
  "ARG10": { "name": "Rodrigo De Paul", "team": "Argentina" },
  "ARG11": { "name": "Exequiel Palacios", "team": "Argentina" },
  "ARG12": { "name": "Leandro Paredes", "team": "Argentina" },
  "ARG13": { "name": "Foto de Equipo", "team": "Argentina" },
  "ARG14": { "name": "Nico Paz", "team": "Argentina" },
  "ARG15": { "name": "Franco Mastantuono", "team": "Argentina" },
  "ARG16": { "name": "Nico Gonzalez", "team": "Argentina" },
  "ARG17": { "name": "Lionel Messi", "team": "Argentina" },
  "ARG18": { "name": "Lautaro Martinez", "team": "Argentina" },
  "ARG19": { "name": "Julian Alvarez", "team": "Argentina" },
  "ARG20": { "name": "Giuliano Simeone", "team": "Argentina" },

  // Algeria
  "ALG1": { "name": "Escudo (Emblem)", "team": "Algeria" },
  "ALG2": { "name": "Alexis Guendouz", "team": "Algeria" },
  "ALG3": { "name": "Ramy Bensebaini", "team": "Algeria" },
  "ALG4": { "name": "Youcef Atal", "team": "Algeria" },
  "ALG5": { "name": "Rayan Aït-Nouri", "team": "Algeria" },
  "ALG6": { "name": "Mohamed Amine Tougai", "team": "Algeria" },
  "ALG7": { "name": "Aïssa Mandi", "team": "Algeria" },
  "ALG8": { "name": "Ismael Bennacer", "team": "Algeria" },
  "ALG9": { "name": "Houssem Aouar", "team": "Algeria" },
  "ALG10": { "name": "Hicham Boudaoui", "team": "Algeria" },
  "ALG11": { "name": "Ramiz Zerrouki", "team": "Algeria" },
  "ALG12": { "name": "Nabil Bentaleb", "team": "Algeria" },
  "ALG13": { "name": "Foto de Equipo", "team": "Algeria" },
  "ALG14": { "name": "Farés Chaibi", "team": "Algeria" },
  "ALG15": { "name": "Riyad Mahrez", "team": "Algeria" },
  "ALG16": { "name": "Said Benrahma", "team": "Algeria" },
  "ALG17": { "name": "Anis Hadj Moussa", "team": "Algeria" },
  "ALG18": { "name": "Amine Gouiri", "team": "Algeria" },
  "ALG19": { "name": "Baghdad Bounedjah", "team": "Algeria" },
  "ALG20": { "name": "Mohammed Amoura", "team": "Algeria" },

  // Austria
  "AUT1": { "name": "Escudo (Emblem)", "team": "Austria" },
  "AUT2": { "name": "Alexander Schlager", "team": "Austria" },
  "AUT3": { "name": "Patrick Pentz", "team": "Austria" },
  "AUT4": { "name": "David Alaba", "team": "Austria" },
  "AUT5": { "name": "Kevin Danso", "team": "Austria" },
  "AUT6": { "name": "Philipp Lienhart", "team": "Austria" },
  "AUT7": { "name": "Stefan Posch", "team": "Austria" },
  "AUT8": { "name": "Phillipp Mwene", "team": "Austria" },
  "AUT9": { "name": "Alexander Prass", "team": "Austria" },
  "AUT10": { "name": "Xaver Schlager", "team": "Austria" },
  "AUT11": { "name": "Marcel Sabitzer", "team": "Austria" },
  "AUT12": { "name": "Konrad Laimer", "team": "Austria" },
  "AUT13": { "name": "Foto de Equipo", "team": "Austria" },
  "AUT14": { "name": "Florian Grillitsch", "team": "Austria" },
  "AUT15": { "name": "Nicolas Seiwald", "team": "Austria" },
  "AUT16": { "name": "Romano Schmid", "team": "Austria" },
  "AUT17": { "name": "Patrick Wimmer", "team": "Austria" },
  "AUT18": { "name": "Christoph Baumgartner", "team": "Austria" },
  "AUT19": { "name": "Michael Gregoritsch", "team": "Austria" },
  "AUT20": { "name": "Marko Arnautović", "team": "Austria" },

  // Jordan
  "JOR1": { "name": "Escudo (Emblem)", "team": "Jordan" },
  "JOR2": { "name": "Yazeed Abulaila", "team": "Jordan" },
  "JOR3": { "name": "Ihsan Haddad", "team": "Jordan" },
  "JOR4": { "name": "Mohammad Abu Hashish", "team": "Jordan" },
  "JOR5": { "name": "Yazan Al-Arab", "team": "Jordan" },
  "JOR6": { "name": "Abdallah Nasib", "team": "Jordan" },
  "JOR7": { "name": "Saleem Obaid", "team": "Jordan" },
  "JOR8": { "name": "Mohammad Abualnadi", "team": "Jordan" },
  "JOR9": { "name": "Ibrahim Saadeh", "team": "Jordan" },
  "JOR10": { "name": "Nizar Al-Rashdan", "team": "Jordan" },
  "JOR11": { "name": "Noor Al-Rawabdeh", "team": "Jordan" },
  "JOR12": { "name": "Mohannad Abu Taha", "team": "Jordan" },
  "JOR13": { "name": "Foto de Equipo", "team": "Jordan" },
  "JOR14": { "name": "Amer Jamous", "team": "Jordan" },
  "JOR15": { "name": "Musa Al-Taamari", "team": "Jordan" },
  "JOR16": { "name": "Yazan Al-Naimat", "team": "Jordan" },
  "JOR17": { "name": "Mahmoud Al-Mardi", "team": "Jordan" },
  "JOR18": { "name": "Ali Olwan", "team": "Jordan" },
  "JOR19": { "name": "Mohammad Abu Zrayq", "team": "Jordan" },
  "JOR20": { "name": "Ibrahim Sabra", "team": "Jordan" },

  // Portugal
  "POR1": { "name": "Escudo (Emblem)", "team": "Portugal" },
  "POR2": { "name": "Diogo Costa", "team": "Portugal" },
  "POR3": { "name": "José Sá", "team": "Portugal" },
  "POR4": { "name": "Ruben Dias", "team": "Portugal" },
  "POR5": { "name": "João Cancelo", "team": "Portugal" },
  "POR6": { "name": "Diogo Dalot", "team": "Portugal" },
  "POR7": { "name": "Nuno Mendes", "team": "Portugal" },
  "POR8": { "name": "Gonçalo Inácio", "team": "Portugal" },
  "POR9": { "name": "Bernardo Silva", "team": "Portugal" },
  "POR10": { "name": "Bruno Fernandes", "team": "Portugal" },
  "POR11": { "name": "Ruben Neves", "team": "Portugal" },
  "POR12": { "name": "Vitinha", "team": "Portugal" },
  "POR13": { "name": "Foto de Equipo", "team": "Portugal" },
  "POR14": { "name": "João Neves", "team": "Portugal" },
  "POR15": { "name": "Cristiano Ronaldo", "team": "Portugal" },
  "POR16": { "name": "Francisco Trincao", "team": "Portugal" },
  "POR17": { "name": "João Felix", "team": "Portugal" },
  "POR18": { "name": "Gonçalo Ramos", "team": "Portugal" },
  "POR19": { "name": "Pedro Neto", "team": "Portugal" },
  "POR20": { "name": "Rafael Leão", "team": "Portugal" },

  // Congo DR
  "COD1": { "name": "Escudo (Emblem)", "team": "Congo DR" },
  "COD2": { "name": "Lionel Mpasi-Nzau", "team": "Congo DR" },
  "COD3": { "name": "Aaron Wan-Bissaka", "team": "Congo DR" },
  "COD4": { "name": "Axel Tuanzebe", "team": "Congo DR" },
  "COD5": { "name": "Arthur Masuaku", "team": "Congo DR" },
  "COD6": { "name": "Chancel Mbemba", "team": "Congo DR" },
  "COD7": { "name": "Joris Kayembe", "team": "Congo DR" },
  "COD8": { "name": "Charles Pickel", "team": "Congo DR" },
  "COD9": { "name": "Ngal'ayel Mukau", "team": "Congo DR" },
  "COD10": { "name": "Edo Kayembe", "team": "Congo DR" },
  "COD11": { "name": "Samuel Moutoussamy", "team": "Congo DR" },
  "COD12": { "name": "Noah Sadiki", "team": "Congo DR" },
  "COD13": { "name": "Foto de Equipo", "team": "Congo DR" },
  "COD14": { "name": "Théo Bongonda", "team": "Congo DR" },
  "COD15": { "name": "Meschak Elia", "team": "Congo DR" },
  "COD16": { "name": "Yoane Wissa", "team": "Congo DR" },
  "COD17": { "name": "Brian Cipenga", "team": "Congo DR" },
  "COD18": { "name": "Fiston Mayele", "team": "Congo DR" },
  "COD19": { "name": "Cédric Bakambu", "team": "Congo DR" },
  "COD20": { "name": "Nathanaël Mbuku", "team": "Congo DR" },

  // Uzbekistan
  "UZB1": { "name": "Escudo (Emblem)", "team": "Uzbekistan" },
  "UZB2": { "name": "Utkir Yusupov", "team": "Uzbekistan" },
  "UZB3": { "name": "Farrukh Savfiev", "team": "Uzbekistan" },
  "UZB4": { "name": "Sherzod Nasrullaev", "team": "Uzbekistan" },
  "UZB5": { "name": "Umar Eshmurodov", "team": "Uzbekistan" },
  "UZB6": { "name": "Husniddin Aliqulov", "team": "Uzbekistan" },
  "UZB7": { "name": "Rustamjon Ashurmatov", "team": "Uzbekistan" },
  "UZB8": { "name": "Khojiakbar Alijonov", "team": "Uzbekistan" },
  "UZB9": { "name": "Abdukodir Khusanov", "team": "Uzbekistan" },
  "UZB10": { "name": "Odiljon Hamrobekov", "team": "Uzbekistan" },
  "UZB11": { "name": "Otabek Shukurov", "team": "Uzbekistan" },
  "UZB12": { "name": "Jamshid Iskanderov", "team": "Uzbekistan" },
  "UZB13": { "name": "Foto de Equipo", "team": "Uzbekistan" },
  "UZB14": { "name": "Azizbek Turgunboev", "team": "Uzbekistan" },
  "UZB15": { "name": "Khojimat Erkinov", "team": "Uzbekistan" },
  "UZB16": { "name": "Eldor Shomurodov", "team": "Uzbekistan" },
  "UZB17": { "name": "Oston Urunov", "team": "Uzbekistan" },
  "UZB18": { "name": "Jaloliddin Masharipov", "team": "Uzbekistan" },
  "UZB19": { "name": "Igor Sergeev", "team": "Uzbekistan" },
  "UZB20": { "name": "Abbosbek Fayzullaev", "team": "Uzbekistan" },

  // Colombia
  "COL1": { "name": "Escudo (Emblem)", "team": "Colombia" },
  "COL2": { "name": "Camilo Vargas", "team": "Colombia" },
  "COL3": { "name": "David Ospina", "team": "Colombia" },
  "COL4": { "name": "Dávinson Sánchez", "team": "Colombia" },
  "COL5": { "name": "Yerry Mina", "team": "Colombia" },
  "COL6": { "name": "Daniel Munoz", "team": "Colombia" },
  "COL7": { "name": "Johan Mojica", "team": "Colombia" },
  "COL8": { "name": "Jhon Lucumí", "team": "Colombia" },
  "COL9": { "name": "Santiago Arias", "team": "Colombia" },
  "COL10": { "name": "Jefferson Lerma", "team": "Colombia" },
  "COL11": { "name": "Kevin Castaño", "team": "Colombia" },
  "COL12": { "name": "Richard Rios", "team": "Colombia" },
  "COL13": { "name": "Foto de Equipo", "team": "Colombia" },
  "COL14": { "name": "James Rodriguez", "team": "Colombia" },
  "COL15": { "name": "Juan Fernando Quintero", "team": "Colombia" },
  "COL16": { "name": "Jorge Carrascal", "team": "Colombia" },
  "COL17": { "name": "Jhon Arias", "team": "Colombia" },
  "COL18": { "name": "Jhon Cordova", "team": "Colombia" },
  "COL19": { "name": "Luis Suarez", "team": "Colombia" },
  "COL20": { "name": "Luis Diaz", "team": "Colombia" },

  // England
  "ENG1": { "name": "Escudo (Emblem)", "team": "England" },
  "ENG2": { "name": "Jordan Pickford", "team": "England" },
  "ENG3": { "name": "John Stones", "team": "England" },
  "ENG4": { "name": "Marc Guéhi", "team": "England" },
  "ENG5": { "name": "Ezri Konsa", "team": "England" },
  "ENG6": { "name": "Trent Alexander-Arnold", "team": "England" },
  "ENG7": { "name": "Reece James", "team": "England" },
  "ENG8": { "name": "Dan Burn", "team": "England" },
  "ENG9": { "name": "Jordan Henderson", "team": "England" },
  "ENG10": { "name": "Declan Rice", "team": "England" },
  "ENG11": { "name": "Jude Bellingham", "team": "England" },
  "ENG12": { "name": "Cole Palmer", "team": "England" },
  "ENG13": { "name": "Foto de Equipo", "team": "England" },
  "ENG14": { "name": "Morgan Rogers", "team": "England" },
  "ENG15": { "name": "Anthony Gordon", "team": "England" },
  "ENG16": { "name": "Phil Foden", "team": "England" },
  "ENG17": { "name": "Bukayo Saka", "team": "England" },
  "ENG18": { "name": "Harry Kane", "team": "England" },
  "ENG19": { "name": "Marcus Rashford", "team": "England" },
  "ENG20": { "name": "Ollie Watkins", "team": "England" },

  // Croatia
  "CRO1": { "name": "Escudo (Emblem)", "team": "Croatia" },
  "CRO2": { "name": "Dominik Livaković", "team": "Croatia" },
  "CRO3": { "name": "Duje Caleta-Car", "team": "Croatia" },
  "CRO4": { "name": "Josko Gvardiol", "team": "Croatia" },
  "CRO5": { "name": "Josip Stanišić", "team": "Croatia" },
  "CRO6": { "name": "Luka Vušković", "team": "Croatia" },
  "CRO7": { "name": "Josip Sutalo", "team": "Croatia" },
  "CRO8": { "name": "Kristijan Jakic", "team": "Croatia" },
  "CRO9": { "name": "Luka Modrić", "team": "Croatia" },
  "CRO10": { "name": "Mateo Kovacic", "team": "Croatia" },
  "CRO11": { "name": "Martin Baturina", "team": "Croatia" },
  "CRO12": { "name": "Lovro Majer", "team": "Croatia" },
  "CRO13": { "name": "Foto de Equipo", "team": "Croatia" },
  "CRO14": { "name": "Mario Pasalic", "team": "Croatia" },
  "CRO15": { "name": "Petar Sucic", "team": "Croatia" },
  "CRO16": { "name": "Ivan Perišić", "team": "Croatia" },
  "CRO17": { "name": "Marco Pasalic", "team": "Croatia" },
  "CRO18": { "name": "Ante Budimir", "team": "Croatia" },
  "CRO19": { "name": "Andrej Kramarić", "team": "Croatia" },
  "CRO20": { "name": "Franjo Ivanovic", "team": "Croatia" },

  // Ghana
  "GHA1": { "name": "Escudo (Emblem)", "team": "Ghana" },
  "GHA2": { "name": "Lawrence Ati Zigi", "team": "Ghana" },
  "GHA3": { "name": "Tariq Lamptey", "team": "Ghana" },
  "GHA4": { "name": "Mohammed Salisu", "team": "Ghana" },
  "GHA5": { "name": "Alidu Seidu", "team": "Ghana" },
  "GHA6": { "name": "Alexander Djiku", "team": "Ghana" },
  "GHA7": { "name": "Gideon Mensah", "team": "Ghana" },
  "GHA8": { "name": "Caleb Yirenkyi", "team": "Ghana" },
  "GHA9": { "name": "Abdul Issahaku Fatawu", "team": "Ghana" },
  "GHA10": { "name": "Thomas Partey", "team": "Ghana" },
  "GHA11": { "name": "Salis Abdul Samed", "team": "Ghana" },
  "GHA12": { "name": "Kamaldeen Sulemana", "team": "Ghana" },
  "GHA13": { "name": "Foto de Equipo", "team": "Ghana" },
  "GHA14": { "name": "Mohammed Kudus", "team": "Ghana" },
  "GHA15": { "name": "Inaki Williams", "team": "Ghana" },
  "GHA16": { "name": "Jordan Ayew", "team": "Ghana" },
  "GHA17": { "name": "André Ayew", "team": "Ghana" },
  "GHA18": { "name": "Joseph Paintsil", "team": "Ghana" },
  "GHA19": { "name": "Osman Bukari", "team": "Ghana" },
  "GHA20": { "name": "Antoine Semenyo", "team": "Ghana" },

  // Panama
  "PAN1": { "name": "Escudo (Emblem)", "team": "Panama" },
  "PAN2": { "name": "Orlando Mosquera", "team": "Panama" },
  "PAN3": { "name": "Luis Mejia", "team": "Panama" },
  "PAN4": { "name": "Fidel Escobar", "team": "Panama" },
  "PAN5": { "name": "Andres Andrade", "team": "Panama" },
  "PAN6": { "name": "Michael Amir Murillo", "team": "Panama" },
  "PAN7": { "name": "Eric Davis", "team": "Panama" },
  "PAN8": { "name": "Jose Cordoba", "team": "Panama" },
  "PAN9": { "name": "Cesar Blackman", "team": "Panama" },
  "PAN10": { "name": "Cristian Martinez", "team": "Panama" },
  "PAN11": { "name": "Aníbal Godoy", "team": "Panama" },
  "PAN12": { "name": "Adalberto Carrasquilla", "team": "Panama" },
  "PAN13": { "name": "Foto de Equipo", "team": "Panama" },
  "PAN14": { "name": "Édgar Bárcenas", "team": "Panama" },
  "PAN15": { "name": "Carlos Harvey", "team": "Panama" },
  "PAN16": { "name": "Ismael Díaz", "team": "Panama" },
  "PAN17": { "name": "Jose Fajardo", "team": "Panama" },
  "PAN18": { "name": "Cecilio Waterman", "team": "Panama" },
  "PAN19": { "name": "Jose Luiz Rodriguez", "team": "Panama" },
  "PAN20": { "name": "Alberto Quintero", "team": "Panama" }
};

export const getStickerNameAndTeam = (code: string): { name: string; team: string } => {
  // If exact match exists
  if (STICKER_NAMES[code]) {
    return STICKER_NAMES[code];
  }

  // Handle fallback or dynamic generation
  const match = code.match(/^([A-Z]+)(\d+)(s)?$/);
  if (match) {
    const rawPrefix = match[1];
    const num = match[2];
    const isSpecial = match[3] === 's';
    
    let teamName = "General";
    if (rawPrefix === 'CC') {
      teamName = "Coca-Cola Special Edition";
      return { name: `Coca-Cola Figu #${num}`, team: teamName };
    }
    
    return { name: `Jugador #${num}${isSpecial ? ' (Especial)' : ''}`, team: teamName };
  }

  return { name: `Figurita ${code}`, team: "Colección" };
};
